"""Criação inicial de todas as tabelas.

Revision ID: 83326e9f098d
Revises: 
Create Date: 2025-07-03 11:49:59.152904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83326e9f098d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('perfil', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_turma', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('url_conteudo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_encontro', sa.DateTime(), nullable=True),
    sa.Column('link_meet', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('fone', sa.String(length=20), nullable=True),
    sa.Column('perfil', sa.String(length=100), nullable=True),
    sa.Column('desafio', sa.String(length=100), nullable=True),
    sa.Column('disponibilidade', sa.String(length=100), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('token_matricula', sa.String(length=32), nullable=True),
    sa.Column('plano_escolhido', sa.String(length=50), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token_matricula')
    )
    op.create_table('turma_modulos',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'modulo_id')
    )
    op.create_table('turma_monitores',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'monitor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_monitores')
    op.drop_table('turma_modulos')
    op.drop_table('registros')
    op.drop_table('encontros')
    op.drop_table('conteudos')
    op.drop_table('avisos')
    op.drop_table('turmas')
    op.drop_table('monitores')
    op.drop_table('modulos')
    # ### end Alembic commands ###
