"""Adiciona tabela Produtos e funil de interesse 2

Revision ID: 885fe8164dd0
Revises: c99826659ce0
Create Date: 2025-07-07 14:32:39.952294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885fe8164dd0'
down_revision = 'c99826659ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_column('programa_interesse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('programa_interesse', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
