"""Adiciona campos detalhados e whatsapp aos registros

Revision ID: 9bc9317337be
Revises: 83326e9f098d
Create Date: 2025-07-04 16:40:13.239778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc9317337be'
down_revision = '83326e9f098d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('programa_interesse', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('perfil_detalhado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('desafio_detalhado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('escolaridade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resumo_jornada', sa.Text(), nullable=True))
        batch_op.drop_column('fone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('resumo_jornada')
        batch_op.drop_column('escolaridade')
        batch_op.drop_column('desafio_detalhado')
        batch_op.drop_column('perfil_detalhado')
        batch_op.drop_column('programa_interesse')
        batch_op.drop_column('whatsapp')

    # ### end Alembic commands ###
