"""Adiciona tabela Produtos e funil de interesse

Revision ID: c99826659ce0
Revises: 9bc9317337be
Create Date: 2025-07-07 11:25:00.123456

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c99826659ce0'
down_revision = '9bc9317337be' # Verifique se este valor corresponde ao seu ficheiro anterior
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('publico_alvo', sa.String(length=50), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('valor', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_publico_alvo'), ['publico_alvo'], unique=False)

    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_interesse_id', sa.Integer(), nullable=True))
        
        # --- INÍCIO DA CORREÇÃO ---
        # Adicionamos um nome explícito para a restrição da chave estrangeira.
        batch_op.create_foreign_key(
            'fk_registros_produto_interesse_id_produtos', # Nome da restrição
            'produtos', 
            ['produto_interesse_id'], 
            ['id']
        )
        # --- FIM DA CORREÇÃO ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        # Também adicionamos o nome aqui para que seja possível reverter a migração
        batch_op.drop_constraint('fk_registros_produto_interesse_id_produtos', type_='foreignkey')
        batch_op.drop_column('produto_interesse_id')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_publico_alvo'))

    op.drop_table('produtos')
    # ### end Alembic commands ###
